WebAppProject/Models/User.cs
using FluentValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using WebAppProject.Data;

namespace WebAppProject.Models
{
    public class User
    {
        [Display(Name ="ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Key] // Primary Key
        [UserIDValidation]
        public int UserID { get; set; }
        
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Display(Name = "Entrance Date")]
        [DataType(DataType.Date)]
        public DateTime EnteranceDate { get; set; }

        [Display(Name = "Property City")]
        public string PropertyCity { get; set; }

        [Display(Name = "Property Street")]
        public string PropertyStreet { get; set; }

        [Display(Name = "Property Street Number")]
        public string PropertyStreetNumber { get; set; } // String and not int for cases like: street number 18א

        [Display(Name = "Property Apartment Number")]
        public int? ApartmentNumber { get; set; } //Not required, only if the property is a building

        [Display(Name = "Admin User")]
        public bool IsAdmin { get; set; }

        [Display(Name = "Username")]
        [UserNameValidation]
        public string UserName { get; set; }

        [Display(Name = "Password")]
        public string Password { get; set; }

        public ICollection<WaterTransaction> WaterTransactions { get; set; }
        public ICollection<ElectricityTransaction> ElectricityTransactions { get; set; }
        public ICollection<PropertyTaxTransaction> PropertyTaxTransactions { get; set; }
    }

    public class UserIDValidation : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var _context = (MvcProjectContext)validationContext
                         .GetService(typeof(MvcProjectContext));

            var usersWithSameID = _context.User.Where(user => user.UserID.ToString().Equals(value.ToString()));

            if (usersWithSameID.Count() != 0)
            {
                return new ValidationResult("Another User With This ID Already Exists");
            }

            return ValidationResult.Success;
        }
    }

    public class UserNameValidation : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var _context = (MvcProjectContext)validationContext
                         .GetService(typeof(MvcProjectContext));

            var usersWithSameUserName = _context.User.Where(user => user.UserName.Equals(value.ToString()));

            if (usersWithSameUserName.Count() != 0)
            {
                return new ValidationResult("This Username Is Already Taken, Please Choose Another One");
            }

            return ValidationResult.Success;
        }
    }
}

WebAppProject/Controllers/ManagerOverviewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Transforms.TimeSeries;
using Newtonsoft.Json;
using WebAppProject.Data;
using WebAppProject.Models;

namespace WebAppProject.Controllers
{
    public class ManagerOverviewController : Controller
    {
        private readonly MvcProjectContext _context;

        public ManagerOverviewController(MvcProjectContext context)
        {
            _context = context;
        }

        // GET: ManagerOverview
        public async Task<IActionResult> Index()
        {
            // Validate logged in here

            ViewModel viewModel = new ViewModel();

            if (isAdmin(this.HttpContext))
            { // Admin
                viewModel.Users = await _context.User.ToListAsync();
                viewModel.WaterTransactions = await _context.WaterTransactions.ToListAsync();
                viewModel.ElectricityTransaction = await _context.ElectricityTransactions.ToListAsync();
                viewModel.PropertyTaxTransactions = await _context.PropertyTaxTransactions.ToListAsync();
                viewModel.ContactApplications = await _context.ContactApplication.ToListAsync();
            } else
            { // Not Admin
                var sessionUserID = HttpContext.Session.GetInt32("UserID");

                viewModel.Users = await _context.User.Where(u => u.UserID == sessionUserID).ToListAsync();
                viewModel.WaterTransactions = await _context.WaterTransactions.Where(u => u.UserID == sessionUserID).ToListAsync();
                viewModel.ElectricityTransaction = await _context.ElectricityTransactions.Where(u => u.UserID == sessionUserID).ToListAsync();
                viewModel.PropertyTaxTransactions = await _context.PropertyTaxTransactions.Where(u => u.UserID == sessionUserID).ToListAsync();
                viewModel.ContactApplications = await _context.ContactApplication.Where(u => u.UserID == sessionUserID).ToListAsync();
            }

            return View(viewModel);
        }

        // GET: ManagerOverview/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (ValidateAdmin(this.HttpContext) != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _context.ViewModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: ManagerOverview/Create
        public IActionResult Create()
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            return View();
        }

        // POST: ManagerOverview/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID")] ViewModel viewModel)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            if (ModelState.IsValid)
            {
                _context.Add(viewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: ManagerOverview/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _context.ViewModel.FindAsync(id);
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: ManagerOverview/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID")] ViewModel viewModel)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            if (id != viewModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ViewModelExists(viewModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: ManagerOverview/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            if (id == null)
            {
                return NotFound();
            }

            var viewModel = await _context.ViewModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // POST: ManagerOverview/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            var viewModel = await _context.ViewModel.FindAsync(id);
            _context.ViewModel.Remove(viewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> SearchAndResult(string SearchDB, string SearchCatagory, Config.TransactionStatus? wantedStatusWater, Config.TransactionStatus? wantedStatusElectricity, Config.TransactionStatus? wantedStatusPropertyTax, Config.TransactionStatus? wantedStatusContactApp, Config.ContactAppType? ContactType, string? SearchKeyWord)
        {
            ViewData["AfterSearch"] = true;

            var NotAdminRedirection = ValidateAdmin(this.HttpContext);
            if (NotAdminRedirection != null)
            {
                return NotAdminRedirection; // Redirect to Home/Index
            }

            ViewModel model = new ViewModel();

            // Init:
            model.Users = null;
            model.WaterTransactions = null;
            model.ElectricityTransaction = null;
            model.PropertyTaxTransactions = null;
            model.ContactApplications = null;

            switch (SearchDB)
            {
                case "User":
                    if (SearchCatagory.Equals("UserID"))
                    {
                       model.Users = await _context.User.Where(user => user.UserID.ToString().Contains(SearchKeyWord)).ToListAsync();
                    }   
                    else if (SearchCatagory.Equals("FirstName"))
                    {
                        model.Users = await _context.User.Where(user => user.FirstName.Contains(SearchKeyWord)).ToListAsync();
                    } 
                    else if (SearchCatagory.Equals("LastName"))
                    {
                        model.Users = await _context.User.Where(user => user.LastName.Contains(SearchKeyWord)).ToListAsync();
                    }
                    else if (SearchCatagory.Equals("Email"))
                    {
                        model.Users = await _context.User.Where(user => user.Email.Contains(SearchKeyWord)).ToListAsync();
                    }
                    else if (SearchCatagory.Equals("City"))
                    {
                        model.Users = await _context.User.Where(user => user.PropertyCity.Contains(SearchKeyWord)).ToListAsync();
                    }
                    else if (SearchCatagory.Equals("Street"))
                    {
                        model.Users = await _context.User.Where(user => user.PropertyStreet.Contains(SearchKeyWord)).ToListAsync();
                    }

                    else if (SearchCatagory.Equals("EnteranceDate")) {

WebAppProject/Views/Users/Create.cshtml
@model WebAppProject.Models.User

@{
    ViewData["Title"] = "Create";
}

    <div class="fade-in">
        <p><strong>Sign Up To <span style="color: #ff0303">H</span><span style="color:whitesmoke">olders</span></strong></p>
    </div>

    <form asp-action="Create" class="register-content">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="first-column">
            <h2 class="register-text">Personal Information <i class="fas fa-user-edit"></i></h2>
            <!--Fields for personal info-->
            <div>
                <label asp-for="FirstName" class="register-label"></label>
                <input asp-for="FirstName" class="register-input" placeholder="Enter your first name" required />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="LastName" class="register-label"></label>
                <input asp-for="LastName" class="register-input" placeholder="Enter your last name" required />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="UserID" class="register-label"></label>
                <input asp-for="UserID" type="number" maxlength="9" id="IDinputField" class="register-input" placeholder="Enter your 9-Digit ID number" required />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="UserName" class="register-label"></label>
                <input asp-for="UserName" class="register-input" placeholder="Enter your user name" required />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Email" class="register-label"></label>
                <input asp-for="Email" class="register-input" placeholder="Enter your email address" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Password" class="register-label"></label>
                <input asp-for="Password" type="password" class="register-input" placeholder="Enter your password" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="second-column">
            <h2 class="register-text">Apartment Information <i class="fas fa-building"></i></h2>
            <!--Fields for Apartment info-->
            <div>
                <label asp-for="EnteranceDate" class="register-label"></label>
                <input asp-for="EnteranceDate" class="register-input" placeholder="Enter the entrance date" required />
                <span asp-validation-for="EnteranceDate" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyCity" class="register-label"></label>
                <input asp-for="PropertyCity" class="register-input" placeholder="Enter the city name" required />
                <span asp-validation-for="PropertyCity" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyStreet" class="register-label"></label>
                <input asp-for="PropertyStreet" class="register-input" placeholder="Enter the street name" required />
                <span asp-validation-for="PropertyStreet" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyStreetNumber" class="register-label"></label>
                <input asp-for="PropertyStreetNumber" class="register-input" placeholder="Enter the house number" required />
                <span asp-validation-for="PropertyStreetNumber" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="ApartmentNumber" class="register-label"></label>
                <input asp-for="ApartmentNumber" class="register-input" placeholder="Enter the apartment and entrance number" />
                <span asp-validation-for="ApartmentNumber" class="text-danger"></span>
            </div>
        </div>
        <div>
            <input type="submit" name="Create" value="Create" class="create-user-button" />
        </div>
    </form>

    <div>
        <a asp-action="Login" class="back-to-login-page">Back to Login Page</a> <!--redirect to home page-->
    </div>

    <script>
        $('form').submit(function (event) {
            if ($('#IDinputField').val().length != 9) {
                alert('ID must be exactly 9-Digits');
                event.preventDefault();
            }
            return; //valid id input
        })
    </script>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

WebAppProject/Views/Users/Delete.cshtml
@model WebAppProject.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteranceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteranceDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyStreet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyStreet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyStreetNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyStreetNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApartmentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApartmentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAppProject/Views/Users/Details.cshtml
@model WebAppProject.Models.User

@{
    ViewData["Title"] = "Details";
}

<!--User Details-->

<h1 class="Page-generic-headline">User Details</h1>



<div class="ManagerOverviewPageWrapper">
    <dl style="height:1200px">
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.EnteranceDate)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.EnteranceDate)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.PropertyCity)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.PropertyCity)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.PropertyStreet)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.PropertyStreet)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.PropertyStreetNumber)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.PropertyStreetNumber)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.ApartmentNumber)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.ApartmentNumber)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "Details-dt">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "Details-dd">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>

<div>
    <a class="create-button" asp-action="Edit" asp-route-id="@Model.UserID">Edit</a>
    <a class="create-button-2" asp-controller="ManagerOverview" asp-action="Index">Back to List</a>
    <a class="create-button-2" asp-action="UserAddressMap" asp-route-id="@Model.UserID">User's Address Map</a><br>
</div>

WebAppProject/Views/Users/Edit.cshtml
@model WebAppProject.Models.User
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "Edit";
}

<!--User Edit-->

<h1 class="Page-generic-headline">Edit User</h1>

<div class="ManagerOverviewPageWrapper">
    <div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="UserID" class="create-label"></label>
                <input asp-for="UserID" class="create-input" disabled="disabled" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="FirstName" class="create-label"></label>
                <input asp-for="FirstName" class="create-input" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="LastName" class="create-label"></label>
                <input asp-for="LastName" class="create-input" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div>
                <input type="hidden" asp-for="UserName" />
                <label asp-for="UserName" class="create-label"></label>
                <input asp-for="UserName" class="create-input" disabled="disabled" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Password" class="create-label"></label>
                <input asp-for="Password" class="create-input" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Email" class="create-label"></label>
                <input asp-for="Email" class="create-input" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="EnteranceDate" class="create-label"></label>
                <input asp-for="EnteranceDate" class="create-input" />
                <span asp-validation-for="EnteranceDate" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyCity" class="create-label"></label>
                <input asp-for="PropertyCity" class="create-input" />
                <span asp-validation-for="PropertyCity" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyStreet" class="create-label"></label>
                <input asp-for="PropertyStreet" class="create-input" />
                <span asp-validation-for="PropertyStreet" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PropertyStreetNumber" class="create-label"></label>
                <input asp-for="PropertyStreetNumber" class="create-input" />
                <span asp-validation-for="PropertyStreetNumber" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="ApartmentNumber" class="create-label"></label>
                <input asp-for="ApartmentNumber" class="create-input" />
                <span asp-validation-for="ApartmentNumber" class="text-danger"></span>
            </div>
            @{
                string isAdmin = Context.Session.GetString("IsAdmin");

                if (isAdmin == "true")
                {
                    <div>
                        <label class="create-label">Admin User</label>
                        <input class="create-input" asp-for="IsAdmin" />
                    </div>
                }
            }
            <div>
                <input type="submit" value="Save" class="create-button" />
            </div>
        </form>
        @{
            string is_Admin = Context.Session.GetString("IsAdmin");
            if (is_Admin == "true") // Only Admin can delete users
            {
                <form asp-action="Delete">
                    <input type="hidden" value="@Model.UserID" name="id" asp-for="UserID" />
                    <input type="submit" id="DeleteSubmitted" value="Delete" class="delete-button" />
                </form>
            }
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    $('#DeleteSubmitted').click(function (event) {
        if (!confirm('Are You Sure You Want To Delete This User?')) {
            event.preventDefault();
        }
    })
</script>

WebAppProject/Views/Users/Index.cshtml
@model IEnumerable<WebAppProject.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnteranceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyStreet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyStreetNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApartmentNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnteranceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyStreet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyStreetNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApartmentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdmin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UserID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UserID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UserID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>