WebAppProject/Controllers/ContactApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppProject.Data;
using WebAppProject.Models;

namespace WebAppProject.Controllers
{
    public class ContactApplicationsController : Controller
    {
        private readonly MvcProjectContext _context;

        public ContactApplicationsController(MvcProjectContext context)
        {
            _context = context;
        }

        // GET: ContactApplications
        public async Task<IActionResult> Index()
        {
            // Validate User logged in here

            if (HttpContext.Session.GetString("IsAdmin").Equals("true"))
            {
                return View(await _context.ContactApplication.ToListAsync());
            }
            else
            {
                var userID = HttpContext.Session.GetInt32("UserID");
                var allowedToSee = _context.ContactApplication.Where(u => u.UserID == userID);
                return View(await allowedToSee.ToListAsync());
            }
        }

        // GET: ContactApplications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactApplication = await _context.ContactApplication
                .FirstOrDefaultAsync(m => m.ContactAppID == id);
            if (contactApplication == null)
            {
                return NotFound();
            }

            // Notice:
            ViewData["ImgPath"] = contactApplication.ImgPath;
            return View(contactApplication);
        }

        // GET: ContactApplications/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContactApplications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Message,ContactType,Img")] ContactApplication contactApplication)
        {
            if (ModelState.IsValid)
            {
                // Init new Application:
                contactApplication.UserID = (int)HttpContext.Session.GetInt32("UserID");
                contactApplication.CreateDate = DateTime.Today;
                contactApplication.Status = Config.TransactionStatus.Open;

                if (contactApplication.Img != null)
                {
                    _context.Add(contactApplication);
                    await _context.SaveChangesAsync(); // Let this contact application get ID from SQL server

                    contactApplication.ImgPath = Image.Save(contactApplication.UserID, contactApplication.Img, getLastContactAppRegisteredID(), "ContactApplication");

                    _context.Update(contactApplication);
                    await _context.SaveChangesAsync(); // Update image path to this contact app ID
                }
                else // (ID is not needed yet because we are not saving an image)
                {
                    contactApplication.ImgPath = "No Image Attached";

                    _context.Add(contactApplication);
                    await _context.SaveChangesAsync(); // let this contact application get ID from SQL server
                }
            }
            return RedirectToAction("Index", "ManagerOverview");
        }

        // GET: ContactApplications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactApplication = await _context.ContactApplication.FindAsync(id);
            if (contactApplication == null)
            {
                return NotFound();
            }
            return View(contactApplication);
        }

        // POST: ContactApplications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Message,ContactType,Img,Status")] ContactApplication ContactAppAfterEdit)
        {
            var ContactAppBeforeEdit = await _context.ContactApplication.FindAsync(id);
            if (ContactAppBeforeEdit == null)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    if (ContactAppAfterEdit.Img != null)
                    {
                        string newImgRelativePath = Image.Edit(ContactAppBeforeEdit.UserID, ContactAppBeforeEdit.ImgPath, ContactAppAfterEdit.Img, ContactAppBeforeEdit.ContactAppID, "ContactApplication");
                        ContactAppBeforeEdit.ImgPath = newImgRelativePath;
                    }

                    ContactAppBeforeEdit.Status = ContactAppAfterEdit.Status;
                    ContactAppBeforeEdit.Title = ContactAppAfterEdit.Title;
                    ContactAppBeforeEdit.Message = ContactAppAfterEdit.Message;
                    ContactAppBeforeEdit.ContactType = ContactAppAfterEdit.ContactType;

                    _context.Update(ContactAppBeforeEdit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactApplicationExists(ContactAppAfterEdit.ContactAppID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "ManagerOverview");
        }

        // GET: ContactApplications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactApplication = await _context.ContactApplication
                .FirstOrDefaultAsync(m => m.ContactAppID == id);
            if (contactApplication == null)
            {
                return NotFound();
            }

            return View(contactApplication);
        }

        // POST: ContactApplications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactApplication = await _context.ContactApplication.FindAsync(id);

            // Delete file from disk (if image attached to this application):
            if (contactApplication.ImgPath.Equals("No Image Attached") == false) // Means there is an image attached to this application
            {
                Image.Delete(contactApplication.ImgPath);
            }

            // Delete transaction from DB:
            _context.ContactApplication.Remove(contactApplication);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "ManagerOverview");
        }

        private bool ContactApplicationExists(int id)
        {
            return _context.ContactApplication.Any(e => e.ContactAppID == id);
        }

        private int getLastContactAppRegisteredID()
        {
            int lastRegisteredID = _context.ContactApplication.Max(app => app.ContactAppID);

            return lastRegisteredID;

        }
    }
}

WebAppProject/Controllers/WaterTransactionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using WebAppProject.Data;
using WebAppProject.Models;

namespace WebAppProject.Controllers
{
    public class WaterTransactionsController : Controller
    {
        private readonly MvcProjectContext _context;

        public WaterTransactionsController(MvcProjectContext context)
        {
            _context = context;
        }

        // GET: WaterTransactions
        public async Task<IActionResult> Index()
        {
            // Validate User logged in here

            if (HttpContext.Session.GetString("IsAdmin").Equals("true")){
                var mvcProjectContext = _context.WaterTransactions.Include(w => w.User);
                return View(await mvcProjectContext.ToListAsync());
            } else {
                var userID = HttpContext.Session.GetInt32("UserID");
                var allowedToSee = _context.WaterTransactions.Where(w => w.UserID == userID);
                return View(await allowedToSee.ToListAsync());
            }
        }

        // GET: WaterTransactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waterTransaction = await _context.WaterTransactions
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WaterMeterID == id);
            if (waterTransaction == null)
            {
                return NotFound();
            }

            // NOTICE: 
            ViewData["ImgPath"] = waterTransaction.ImgPath;
            return View(waterTransaction);
        }

        // GET: WaterTransactions/Create
        public IActionResult Create()
        {
            ViewData["UserID"] = new SelectList(_context.User, "UserID", "UserID");
            return View();
        }

        // POST: WaterTransactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,WaterMeterLastReadDate,WaterMeterID,WaterMeterImg,ImgPath")] WaterTransaction waterTransaction)
        {
            if (ModelState.IsValid)
            {
                waterTransaction.UserID = (int)HttpContext.Session.GetInt32("UserID");

                string ImgPathAfterSave = Image.Save(waterTransaction.UserID, waterTransaction.WaterMeterImg, waterTransaction.WaterMeterID, "Water");
                if (ImgPathAfterSave == null) // Another file with same name is already exist - "UserID-WaterMeterID" has to be unique
                {
                    ModelState.AddModelError("", "Another transaction with the same User ID Water Meter ID is already exist.");
                    return View();
                }

                waterTransaction.Status = Config.TransactionStatus.Open; // Init new transaction status

                waterTransaction.ImgPath = ImgPathAfterSave;
                _context.Add(waterTransaction);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "ManagerOverview");
            }

            ViewData["UserID"] = new SelectList(_context.User, "UserID", "UserID", waterTransaction.UserID);
            return View(waterTransaction);
        }

        // GET: WaterTransactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waterTransaction = await _context.WaterTransactions.FindAsync(id);
            if (waterTransaction == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.User, "UserID", "UserID", waterTransaction.UserID);
            return View(waterTransaction);
        }

        // POST: WaterTransactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserID,WaterMeterLastReadDate,WaterMeterID,WaterMeterImg,ImgPath,Status")] WaterTransaction waterTransactionAfterEdit)
        {
            var waterTransactionBeforeEdit = await _context.WaterTransactions.FindAsync(id);
            if (waterTransactionBeforeEdit == null)
            {
                return NotFound();
            }

            ModelState.Remove("WaterMeterID"); // Disabled field, can't be editted

            if (ModelState.IsValid)
            {
                try
                {
                    if (waterTransactionAfterEdit.WaterMeterImg != null)
                    {
                        string newImgRelativePath = Image.Edit(waterTransactionBeforeEdit.UserID, waterTransactionBeforeEdit.ImgPath, waterTransactionAfterEdit.WaterMeterImg, waterTransactionBeforeEdit.WaterMeterID, "Water");
                        waterTransactionBeforeEdit.ImgPath = newImgRelativePath;
                    }

                    waterTransactionBeforeEdit.Status = waterTransactionAfterEdit.Status;
                    waterTransactionBeforeEdit.WaterMeterLastReadDate = waterTransactionAfterEdit.WaterMeterLastReadDate;
                    _context.Update(waterTransactionBeforeEdit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WaterTransactionExists(waterTransactionAfterEdit.WaterMeterID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["UserID"] = new SelectList(_context.User, "UserID", "UserID", waterTransactionAfterEdit.UserID);
            return RedirectToAction("Index", "ManagerOverview");
        }

        // GET: WaterTransactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waterTransaction = await _context.WaterTransactions
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WaterMeterID == id);
            if (waterTransaction == null)
            {
                return NotFound();
            }

            return View(waterTransaction);
        }

        // POST: WaterTransactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var waterTransaction = await _context.WaterTransactions.FindAsync(id);

            // Delete file from disk:
            Image.Delete(waterTransaction.ImgPath);

            // Delete transaction from DB:
            _context.WaterTransactions.Remove(waterTransaction);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "ManagerOverview");
        }

        private bool WaterTransactionExists(int id)
        {
            return _context.WaterTransactions.Any(e => e.WaterMeterID == id);
        }
    }
}

WebAppProject/Views/ManagerOverview/Create.cshtml
@model WebAppProject.Models.ViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppProject/Views/ManagerOverview/Delete.cshtml
@model WebAppProject.Models.ViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ViewModel</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAppProject/Views/ManagerOverview/Details.cshtml
@model WebAppProject.Models.ViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ViewModel</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebAppProject/Views/ManagerOverview/Edit.cshtml
@model WebAppProject.Models.ViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppProject/Views/ManagerOverview/Index.cshtml
@model ViewModel
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "Manager Overview";
}


<!--ManagerOverview-->

<h1 class="Page-generic-headline">Overview</h1>

<aside>
    <h2>Welcome!</h2>
    <ul>
        <li>On this page you will automatically see all the registered transactions related to your account.<hr /></li>
        <li>For transaction create and other services you can toggle the nav bar on the top of your screen.<hr /></li>
        <li>We wish you a happy staying and a nice day.<br /><hr /></li>
        <li style="text-align:right;">The <span style="color:red; font-weight:bold;">H</span><span style="color:white; font-weight:bold">olders</span> team</li>
    </ul>
</aside>

@if (Context.Session.GetString("IsAdmin").Equals("true"))
{
    <a class="Search-button" asp-action="SearchAndResult">Search <i class="fas fa-search"></i></a>

    <div class="ManagerOverviewPageWrapper" style="margin-bottom:2%">
        <h3>Registered Users List</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        User ID
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Email Address
                    </th>
                    <th>
                        Enterance Date
                    </th>
                    <th>
                        City
                    </th>
                    <th>
                        Street
                    </th>
                    <th>
                        Street Number
                    </th>
                    <th>
                        Apartment Number
                    </th>
                    <th>
                        Is Admin
                    </th>
                    <th>
                        User Name
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (User user in Model.Users)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => user.UserID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.EnteranceDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.PropertyCity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.PropertyStreet)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.PropertyStreetNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.ApartmentNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.IsAdmin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => user.UserName)
                        </td>
                        <td class="OverviewActions">
                            <a asp-controller="Users" asp-action="Edit" asp-route-id="@user.UserID">Edit <i class="far fa-edit"></i></a> |
                            <a asp-controller="Users" asp-action="Details" asp-route-id="@user.UserID">Details <i class="fas fa-info"></i></a> |
                            <a asp-controller="Users" asp-action="Edit" asp-route-id="@user.UserID">Delete <i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="clear28"></div>
}

@if (Context.Session.GetString("IsAdmin").Equals("true"))
{
 <h1 class="Page-generic-headline">All Listed Transactions</h1>

}

<div class="ManagerOverviewPageWrapper">
    <h3>Registered Water Transactions</h3>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Water Meter ID
                </th>
                <th>
                    Water Meter Last Read Date
                </th>
                <th>
                    Image File Path
                </th>
                <th>
                    User ID
                </th>
                <th style="text-align:right">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (WaterTransaction transaction in Model.WaterTransactions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.WaterMeterID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.WaterMeterLastReadDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.ImgPath)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.User.UserID)
                    </td>
                    <td style="text-align:right">
                        @Html.DisplayFor(modelItem => transaction.Status)
                    </td>
                    <td class="OverviewActions">
                        <a asp-controller="WaterTransactions" asp-action="Edit" asp-route-id="@transaction.WaterMeterID">Edit <i class="far fa-edit"></i></a> |
                        <a asp-controller="WaterTransactions" asp-action="Details" asp-route-id="@transaction.WaterMeterID">Details <i class="fas fa-info"></i></a> |
                        <a asp-controller="WaterTransactions" asp-action="Edit" asp-route-id="@transaction.WaterMeterID">Delete <i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="clear28"></div>

    <h3>Registered Electricity Transactions</h3>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Electricity Meter ID
                </th>
                <th>
                    Electricity Meter Last Read Date
                </th>
                <th>
                    Image File Path
                </th>
                <th>
                    User ID
                </th>
                <th style="text-align:right">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (ElectricityTransaction transaction in Model.ElectricityTransaction)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.ElectricityMeterID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.ElectricityMeterLastRead)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.ImgPath)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.User.UserID)
                    </td>
                    <td style="text-align:right">
                        @Html.DisplayFor(modelItem => transaction.Status)
                    </td>
                    <td class="OverviewActions">
                        <a asp-controller="ElectricityTransactions" asp-action="Edit" asp-route-id="@transaction.ElectricityMeterID">Edit <i class="far fa-edit"></i></a> |
                        <a asp-controller="ElectricityTransactions" asp-action="Details" asp-route-id="@transaction.ElectricityMeterID">Details <i class="fas fa-info"></i></a> |
                        <a asp-controller="ElectricityTransactions" asp-action="Edit" asp-route-id="@transaction.ElectricityMeterID">Delete <i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="clear28"></div>

    <h3>Registered Proprty Tax Transactions</h3>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Property ID
                </th>
                <th>
                    Image File Path
                </th>
                <th>
                    User ID
                </th>
                <th style="text-align:right">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (PropertyTaxTransaction transaction in Model.PropertyTaxTransactions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.PropertyID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.ImgPath)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => transaction.User.UserID)
                    </td>
                    <td style="text-align:right">
                        @Html.DisplayFor(modelItem => transaction.Status)
                    </td>
                    <td class="OverviewActions">
                        <a asp-controller="PropertyTaxTransactions" asp-action="Edit" asp-route-id="@transaction.PropertyID">Edit <i class="far fa-edit"></i></a> |
                        <a asp-controller="PropertyTaxTransactions" asp-action="Details" asp-route-id="@transaction.PropertyID">Details <i class="fas fa-info"></i></a> |
                        <a asp-controller="PropertyTaxTransactions" asp-action="Edit" asp-route-id="@transaction.PropertyID">Delete <i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div class="clear28"></div>

    <h3>Contact Applications</h3>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Application ID
                </th>
                <th>
                    Client ID
                </th>
                <th>
                    Transaction Type
                </th>
                <th>
                    Title
                </th>
                <th>
                    Meesage
                </th>
                <th>
                    Creation Date
                </th>
                <th style="text-align:right">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (ContactApplication application in Model.ContactApplications)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => application.ContactAppID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => application.UserID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => application.ContactType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => application.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => application.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => application.CreateDate)
                    </td>
                    <td style="text-align:right">
                        @Html.DisplayFor(modelItem => application.Status)
                    </td>
                    <td class="OverviewActions">
                        <a asp-controller="ContactApplications" asp-action="Edit" asp-route-id="@application.ContactAppID">Edit <i class="far fa-edit"></i> </a> |
                        <a asp-controller="ContactApplications" asp-action="Details" asp-route-id="@application.ContactAppID">Details <i class="fas fa-info"></i></a> |
                        <a asp-controller="ContactApplications" asp-action="Edit" asp-route-id="@application.ContactAppID">Delete <i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="clear28"></div>
</div>

WebAppProject/Views/ManagerOverview/Predications.cshtml
<h1 class="Page-generic-headline">Transaction Predictions:</h1>

<div class="ManagerOverviewPageWrapper">

    @if (ViewData["ErrorMsg"].Equals("null"))
    {
        <p class="predictions">Listed below is the amount of users predicted to change their apartment in next year's Q1, divided by month:</p>

        <h3>January @ViewData["NextYearNumber"]: @ViewData["In1MonthsFromNowForecast"] Entrances</h3>
        <h3>February @ViewData["NextYearNumber"]: @ViewData["In2MonthsFromNowForecast"] Entrances</h3>
        <h3>March @ViewData["NextYearNumber"]: @ViewData["In3MonthsFromNowForecast"] Entrances</h3>
    } else
    {
        <h3>@ViewData["ErrorMsg"]</h3>
    }


</div>